version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: locadora_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - elasticsearch
      - redis  # Adicionado
    networks:
      - appnet

  postgres:
    image: postgres:15
    container_name: locadora_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: locadora
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: locadora_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - appnet

  redis:  # Novo serviço Redis
    image: redis:latest
    container_name: locadora_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
